"""Inline Archivist — zero-cost pipeline journaling.

Captures council, planning, and execution decisions into HEROLOG.md
as structured entries. Only Phase 3 (post-mission synthesis) spawns
the MiniMax M2.7 agent; Phases 0-2 are pure Python formatting.
"""

from datetime import datetime
from pathlib import Path


def _ensure_herolog(journal_path: Path) -> None:
    """Create HEROLOG.md with header if it doesn't exist."""
    if not journal_path.exists():
        journal_path.parent.mkdir(parents=True, exist_ok=True)
        journal_path.write_text(
            "# HEROLOG — Pipeline Journal\n\n"
            "_Auto-generated by HERO Archivist (inline mode)_\n\n"
        )


def _append(journal_path: Path, entry: str) -> None:
    """Append a structured entry to HEROLOG.md."""
    _ensure_herolog(journal_path)
    with open(journal_path, "a") as f:
        f.write(entry)


# ── Phase 0 — Council Summary ────────────────────────────────────────


def capture_council(
    pipeline_id: str,
    task: str,
    sandbox: str,
    participants: list[str],
    root_causes: list[str],
    disagreements: list[str] | None = None,
    consensus: str = "",
    rejected: list[str] | None = None,
    journal_path: Path | None = None,
) -> str:
    """Format and return a Phase 0 council summary entry."""
    root_bullets = "\n".join(f"- {rc}" for rc in (root_causes or [])) or "- (none)"
    disagree_bullets = "\n".join(f"- {d}" for d in (disagreements or [])) or "- (full agreement)"
    rejected_bullets = "\n".join(f"- {r}" for r in (rejected or [])) or "- (none)"

    entry = f"""
## Phase 0 — Council Summary

**Pipeline:** {pipeline_id}
**Task:** {task}
**Sandbox:** {sandbox}
**Timestamp:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

### Participants
{', '.join(participants)}

### Root Causes Identified
{root_bullets}

### Consensus
{consensus}

### Disagreements
{disagree_bullets}

### Rejected Alternatives
{rejected_bullets}

---
"""
    if journal_path:
        _append(journal_path, entry)
    return entry


# ── Phase 1 — Planning Summary ───────────────────────────────────────


def capture_planning(
    pipeline_id: str,
    task: str,
    sandbox: str,
    project_type: str,
    subtasks: list[dict],
    analysis_result: str = "",
    journal_path: Path | None = None,
) -> str:
    """Format and return a Phase 1 planning summary entry."""
    task_list = "\n".join(
        f"{i+1}. **{st.get('title', '?')}** — {st.get('goal', '')[:120]}"
        for i, st in enumerate(subtasks)
    )
    file_list = "\n".join(
        f"- {st.get('files', 'auto')}" for st in subtasks
    )

    entry = f"""
## Phase 1 — Planning Summary

**Pipeline:** {pipeline_id}
**Task:** {task}
**Sandbox:** {sandbox}
**Project type:** {project_type}
**Subtasks generated:** {len(subtasks)}

### Task Decomposition
{task_list}

### File Scope
{file_list}

### Analysis
{analysis_result or '(none)'}

---
"""
    if journal_path:
        _append(journal_path, entry)
    return entry


# ── Phase 2 — Execution (per-soldier hook) ──────────────────────────


def capture_soldier(
    pipeline_id: str,
    sandbox: str,
    task_id: str,
    soldier_label: str,
    status: str,
    result: str | None = None,
    diff_summary: str | None = None,
    journal_path: Path | None = None,
    diffs_path: Path | None = None,
) -> str:
    """Format and return a Phase 2 soldier execution entry.

    Also appends raw diff to soldier_diffs.md if diffs_path is given.
    """
    entry = f"""
### Soldier: {soldier_label}
**Task ID:** {task_id}
**Status:** {status}
**Timestamp:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

**Result:**
{(result or '(no result)')[:500]}

**Files changed:**
{diff_summary or '- (not captured)'}

---
"""
    if journal_path:
        _append(journal_path, entry)

    if diff_summary and diffs_path:
        diffs_path.parent.mkdir(parents=True, exist_ok=True)
        with open(diffs_path, "a") as f:
            f.write(f"\n## {soldier_label} — {task_id}\n\n{diff_summary}\n")

    return entry


# ── Utility ──────────────────────────────────────────────────────────


def get_herolog_tail(journal_path: Path, max_chars: int = 4000) -> str:
    """Read the last max_chars of HEROLOG.md for injection into Phase 3."""
    if not journal_path.exists():
        return ""
    text = journal_path.read_text()
    if len(text) <= max_chars:
        return text
    return "...[truncated]...\n" + text[-max_chars:]
